# Sample workflow for building and deploying a Hugo site to GitHub Pages
name: Deploy Hugo site to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches:
      - main
      - staging

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

# Default to bash
defaults:
  run:
    shell: bash

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.134.2
    steps:
      - name: SETUP - Install Hugo CLI
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb

      - name: SETUP - Install Dart Sass
        run: sudo snap install dart-sass

      - name: SETUP - Code Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: SETUP - Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Install Node.js dependencies
        run: "[[ -f package-lock.json || -f npm-shrinkwrap.json ]] && npm ci || true"

      - name: BUILD - Building site with Hugo
        env:
          HUGO_CACHEDIR: ${{ runner.temp }}/hugo_cache
          HUGO_ENVIRONMENT: production
          TZ: America/New_York
        run: |
          hugo \
            --gc \
            --minify \
            --baseURL "${{ steps.pages.outputs.base_url }}/"

      - name: BUILD - Create CNAME file for custom domain
        run: echo "kennethho.ca" > ./public/CNAME

      - name: TEST - Validate HTML
        run: |
          npm install htmlhint -g
          htmlhint public/**/*.html
  
      - name: TEST - Check for Broken Links
        run: |
          npm install linkinator -g
          linkinator "public" --recursive --skip "https://staging.mydomain.tld"
  
      - name: TEST - Lighthouse Performance Test
        uses: treosh/lighthouse-ci-action@v5
        with:
          urls: https://staging.mydomain.tld/
          configPath: ./lighthouse-config.js
  
      - name: TEST - Accessibility Test with aXe
        run: |
          npm install axe-cli -g
          axe https://staging.mydomain.tld
  
      - name: TEST - Security Headers Test
        run: |
          curl -I https://staging.mydomain.tld | grep -E 'Strict-Transport-Security|Content-Security-Policy|X-Frame-Options'

      - name: BUILD - Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
